version: '3'

services:
  jenkins-ci:
    build:
      context: ./jenkins-server
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID}
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      - ci

  anchore-engine:
    image: anchore/anchore-engine:latest
    depends_on:
      - anchore-db
    ports:
      - "8228:8228"
      - "8338:8338"
    volumes:
      - ./anchore/config:/config/:Z
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    environment:
      - ANCHORE_ADMIN_PASSWORD=4dm1n
      - ANCHORE_HOST_ID=anchore-engine
      - ANCHORE_ENDPOINT_HOSTNAME=anchore-engine
      - ANCHORE_DB_HOST_ID=anchore-db
      - ANCHORE_DB_USER=postgres
      - ANCHORE_DB_PASS=mysecretpassword
    networks:
      - ci

  anchore-db:
    image: "postgres:9"
    volumes:
      - "./anchore/db:/var/lib/postgresql/data/pgdata/:Z"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      - ci

networks:
  ci:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400